[Service]
ExecStartPre=/usr/bin/chown -R thatch:thatch /srv/git/Thatch.Server.git
ExecStartPre=/bin/chmod -R g+rwX /srv/git/Thatch.Server.git
ExecStartPre=/usr/bin/find /srv/git/Thatch.Server.git -type d -exec /bin/chmod g+s {} +
