import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { buildOpenApiSpec } from "../server/src/routes/openapi.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const defaultOutputPath = path.join(repoRoot, "ui/src/api/generated/openapi-client.d.ts");
const sourcePath = "server/src/routes/openapi.ts#buildOpenApiSpec";

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalize);
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, canonicalize(entry)]),
    );
  }
  return value;
}

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .replace(/"([^"\\]*(?:\\.[^"\\]*)*)":/g, (_match, key: string) => `${JSON.stringify(key)}:`)
    .replace(/\n/g, "\n  ");
}

function buildGeneratedClient() {
  const spec = canonicalize(buildOpenApiSpec());
  const json = JSON.stringify(spec, null, 2);
  const hash = createHash("sha256").update(json).digest("hex");
  const contractIndex = {
    source: sourcePath,
    sourceSha256: hash,
    paths: Object.fromEntries(
      Object.entries((spec as { paths?: Record<string, Record<string, unknown>> }).paths ?? {}).map(([routePath, pathItem]) => [
        routePath,
        Object.fromEntries(
          Object.entries(pathItem).map(([method, operation]) => {
            const typedOperation = operation as Record<string, unknown>;
            const requestBody = typedOperation.requestBody
              ? createHash("sha256").update(JSON.stringify(typedOperation.requestBody)).digest("hex")
              : null;
            return [
              method,
              {
                summary: typedOperation.summary ?? null,
                requestBodySha256: requestBody,
                responses: Object.keys((typedOperation.responses as Record<string, unknown> | undefined) ?? {}).sort(),
                security: typedOperation.security ?? null,
              },
            ];
          }),
        ),
      ]),
    ),
  };

  return `// Generated by scripts/check-portal-contract.ts. Do not edit by hand.
// Source OpenAPI artifact: ${sourcePath}
// Source OpenAPI sha256: ${hash}

export declare const paperclipOpenApiContract: ${literal(contractIndex)};

export type PaperclipOpenApiContract = typeof paperclipOpenApiContract;
export type PaperclipOpenApiPaths = PaperclipOpenApiContract["paths"];
`;
}

function usage(): never {
  console.error("Usage: check-portal-contract.ts [--write] [--fixture <path>] [--expect-stale]");
  process.exit(2);
}

let write = false;
let fixturePath: string | null = null;
let expectStale = false;

for (let index = 2; index < process.argv.length; index += 1) {
  const arg = process.argv[index];
  if (arg === "--write") {
    write = true;
  } else if (arg === "--fixture") {
    const value = process.argv[index + 1];
    if (!value) usage();
    fixturePath = path.resolve(repoRoot, value);
    index += 1;
  } else if (arg === "--expect-stale") {
    expectStale = true;
  } else {
    usage();
  }
}

if (write && (fixturePath || expectStale)) usage();
if (expectStale && !fixturePath) usage();

const outputPath = fixturePath ?? defaultOutputPath;
const generated = buildGeneratedClient();

if (write) {
  fs.mkdirSync(path.dirname(defaultOutputPath), { recursive: true });
  fs.writeFileSync(defaultOutputPath, generated);
  console.log(`Wrote Portal OpenAPI contract client: ${path.relative(repoRoot, defaultOutputPath)}`);
  process.exit(0);
}

const actual = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
const isFresh = actual === generated;

if (expectStale) {
  if (!isFresh) {
    console.log(`Stale Portal OpenAPI contract fixture detected as expected: ${path.relative(repoRoot, outputPath)}`);
    process.exit(0);
  }
  console.error(`Expected stale Portal OpenAPI contract fixture, but it matched: ${path.relative(repoRoot, outputPath)}`);
  process.exit(1);
}

if (!isFresh) {
  console.error(`Portal OpenAPI contract client is stale: ${path.relative(repoRoot, outputPath)}`);
  console.error("Run: pnpm --filter @paperclipai/server exec tsx ../scripts/check-portal-contract.ts --write");
  process.exit(1);
}

console.log(`Portal OpenAPI contract client is fresh: ${path.relative(repoRoot, outputPath)}`);
